// Auto-generated from LevCharity-2.0-QA-Plan.pdf (June 2026).
// Static QA plan content: module headers and the tasks under each.
// Task *statuses* are stored separately in Firestore (see db.js).

export const QA_PLAN = [
  {
    code: '01',
    title: 'Onboarding & account setup',
    tasks: [
      { id: 'OB001', feature: 'Initial setup checklist is visible on first login', verify: 'Checklist items guide admin through all 5 setup steps in correct order', priority: 'P1', type: 'Functional' },
      { id: 'OB002', feature: 'Organization name saves and propagates', verify: 'Name appears on receipts, email headers, and all public-facing pages', priority: 'P0', type: 'Integration' },
      { id: 'OB003', feature: 'Charitable number field saves correctly', verify: 'Appears on generated receipt PDFs', priority: 'P0', type: 'Functional' },
      { id: 'OB004', feature: 'Contact details (email, phone, website, address) save', verify: 'All fields persist and appear in correct locations (receipts, correspondence)', priority: 'P1', type: 'Functional' },
      { id: 'OB005', feature: 'Site direction: LTR and RTL toggle', verify: 'Entire admin portal and public pages flip direction without layout breaks', priority: 'P1', type: 'UI/Visual' },
      { id: 'OB006', feature: 'Legal page URLs save and link correctly', verify: 'Privacy policy, Terms of Service, and Cookie policy URLs are stored and linkable', priority: 'P1', type: 'Functional' },
      { id: 'OB007', feature: 'User invitation flow end-to-end', verify: 'Invite email is sent, link works, invited user can set password and log in', priority: 'P0', type: 'E2E' },
      { id: 'OB008', feature: 'Role assignment during invitation', verify: 'Admin can assign role at invite time; invited user inherits correct permissions on first login', priority: 'P0', type: 'E2E' },
      { id: 'OB009', feature: 'Resend invitation', verify: 'Resend link delivers a fresh password reset email; old link is invalidated', priority: 'P1', type: 'Functional' },
      { id: 'OB010', feature: 'Cannot delete own account', verify: 'Delete option hidden for own user; no API bypass possible', priority: 'P0', type: 'Security' },
      { id: 'OB011', feature: 'Settings require correct permissions to save', verify: 'User without settings.edit cannot save; receives appropriate error message', priority: 'P0', type: 'Security' },
      { id: 'OB012', feature: 'Platform structure navigation loads correctly', verify: 'All 8 core sidebar areas load; RBAC hides areas the user lacks access to', priority: 'P1', type: 'Functional' },
    ],
  },
  {
    code: '02',
    title: 'Branding',
    tasks: [
      { id: 'BR001', feature: 'Logo upload via Media Picker', verify: 'Logo displays in admin sidebar immediately after upload without hard refresh', priority: 'P1', type: 'Functional' },
      { id: 'BR002', feature: 'Favicon upload', verify: 'Favicon appears in browser tab after hard refresh', priority: 'P2', type: 'Functional' },
      { id: 'BR003', feature: 'Header font selection Google Fonts)', verify: 'Selected heading font renders on all public-facing H1H6 elements', priority: 'P1', type: 'UI/Visual' },
      { id: 'BR004', feature: 'Body font selection', verify: 'Selected body font renders on paragraphs, labels, and UI elements', priority: 'P1', type: 'UI/Visual' },
      { id: 'BR005', feature: '9 brand colors save and apply', verify: 'Primary, hover, secondary, secondary text, tertiary, tertiary GP, text, campaigned, button all apply to public pages', priority: 'P0', type: 'UI/Visual' },
      { id: 'BR006', feature: 'Color picker: hex input and swatch both work', verify: 'Manual hex entry and swatch selection both save and render correctly', priority: 'P2', type: 'Functional' },
      { id: 'BR007', feature: 'Button rounding: Pill / Rounded / Rectangle', verify: 'Selected rounding style applies to all buttons: donation forms, campaign pages, event pages, headers', priority: 'P1', type: 'UI/Visual' },
      { id: 'BR008', feature: 'Header builder: Main site header', verify: 'Drag-and-drop items render correctly; live preview matches public output', priority: 'P1', type: 'UI/Visual' },
      { id: 'BR009', feature: 'Header builder: Default campaign header', verify: 'Campaign-specific items Search Fundraiser, Sign Up, Donate, My Account) render', priority: 'P1', type: 'UI/Visual' },
      { id: 'BR010', feature: 'Header item visibility toggle', verify: 'Hiding an item in the builder removes it from the public header without breaking layout', priority: 'P2', type: 'Functional' },
      { id: 'BR011', feature: 'Mobile menu: Slide In and Dropdown modes', verify: 'Both mobile menu styles render correctly on 768px viewport', priority: 'P1', type: 'UI/Visual' },
      { id: 'BR012', feature: 'Per-language header templates', verify: 'Editing English header does not affect Hebrew; changes save per-language', priority: 'P1', type: 'Functional' },
      { id: 'BR013', feature: 'Headers moved to Website Builder → Templates', verify: 'Legacy branding page no longer shows header editor; link to new location works', priority: 'P2', type: 'Functional' },
    ],
  },
  {
    code: '03',
    title: 'Admin tools: users, roles & permissions',
    tasks: [
      { id: 'AT001', feature: 'User list: search, sort, pagination', verify: 'Users searchable by name and email; sortable columns; pagination works for large lists', priority: 'P1', type: 'Functional' },
      { id: 'AT002', feature: 'Edit user: update name, email, password, role', verify: 'All editable fields persist; role change takes effect on next page load', priority: 'P0', type: 'Functional' },
      { id: 'AT003', feature: 'User export: CSV and XLSX', verify: 'Export includes selected columns in chosen order; filtered results export correctly', priority: 'P2', type: 'Functional' },
      { id: 'AT004', feature: 'Create role with custom permissions', verify: 'New role saves with selected permissions; assigned users immediately inherit access', priority: 'P0', type: 'Functional' },
      { id: 'AT005', feature: 'Edit role: add/remove permissions', verify: 'Removing a permission immediately revokes access for assigned users on next load', priority: 'P0', type: 'Security' },
      { id: 'AT006', feature: 'Super Admin: cannot be edited or deleted', verify: 'Three-dot menu does not appear for super_admin; no API bypass works', priority: 'P0', type: 'Security' },
      { id: 'AT007', feature: 'Super Admin bypasses all permission checks', verify: 'Super admin user can access all routes and features regardless of configuration', priority: 'P0', type: 'Security' },
      { id: 'AT008', feature: 'Permission group toggles', verify: 'Clicking group checkbox selects/deselects all permissions in that group', priority: 'P2', type: 'Functional' },
      { id: 'AT009', feature: 'System roles show badge and cannot be deleted', verify: '"System" badge visible; Delete option absent from system role rows', priority: 'P1', type: 'Functional' },
      { id: 'AT010', feature: 'All 17 permission groups present and functional', verify: 'Users, Roles, Contacts, Orders, Subscriptions, Installments, Sponsorships, Donation Forms, Campaigns, Events, Fundraisers, Teams, Emails, Reports, Settings, Audit Logs all appear and enforce correctly', priority: 'P0', type: 'Security' },
      { id: 'AT011', feature: 'Frontend permission gates: buttons hidden when no access', verify: 'Add New, Edit, Delete buttons are absent when user lacks the respective permission', priority: 'P0', type: 'Security' },
      { id: 'AT012', feature: 'Backend route permission middleware', verify: 'Direct URL/API access to protected routes returns 403 for users without permission', priority: 'P0', type: 'Security' },
    ],
  },
  {
    code: '04',
    title: 'Advanced settings',
    tasks: [
      { id: 'AS001', feature: 'Table row defaults 10/25/50/100', verify: 'Selected default applies to all data tables across the platform', priority: 'P2', type: 'Functional' },
      { id: 'AS002', feature: 'Max scheduled exports setting', verify: 'Limit enforces correctly; UI shows error when exceeded', priority: 'P2', type: 'Functional' },
      { id: 'AS003', feature: 'Enable pledges toggle', verify: 'When enabled, pledge option appears on checkout; when disabled, it is absent', priority: 'P1', type: 'Functional' },
      { id: 'AS004', feature: 'Duplicate detection and auto-merge', verify: 'Duplicate contacts are flagged; auto-merge correctly combines records without data loss', priority: 'P1', type: 'Functional' },
      { id: 'AS005', feature: 'Email open and link click tracking', verify: 'Open events recorded; link clicks logged; engagement scores update', priority: 'P2', type: 'Integration' },
      { id: 'CH001', feature: 'Minimum donation amount enforces on public form', verify: 'Submitting an amount below minimum is rejected with clear error message', priority: 'P0', type: 'Functional' },
      { id: 'CH002', feature: 'Credit card fee percentage shows/hides correctly', verify: 'Fee displays when 0 and preselected toggle works; donors can opt in/out', priority: 'P1', type: 'Functional' },
      { id: 'CH003', feature: 'Checkout field hide/require toggles', verify: 'Hidden fields absent from form; required fields block submission when empty', priority: 'P0', type: 'Functional' },
      { id: 'CH004', feature: 'Phone country dial prefix: keyboard accessible', verify: 'Enter opens selector, arrow keys navigate, Enter selects, Escape closes', priority: 'P1', type: 'Accessibility' },
      { id: 'CH005', feature: 'Donate on behalf of organization checkbox', verify: 'Organization name field appears; captures and stores correctly', priority: 'P2', type: 'Functional' },
      { id: 'CH006', feature: 'Terms checkbox shows and blocks submission when unchecked', verify: 'When enabled, form cannot be submitted without accepting terms', priority: 'P1', type: 'Functional' },
      { id: 'CH007', feature: 'One-time / monthly frequency toggle and defaults', verify: 'Pre-selected frequency is correct; hiding tabs shows only default', priority: 'P1', type: 'Functional' },
      { id: 'CH008', feature: 'Suggested amounts render correctly', verify: 'Pre-set amount buttons appear in configured order; clicking pre-fills amount field', priority: 'P1', type: 'Functional' },
      { id: 'CH009', feature: 'Donor comment field', verify: 'Comment saves with donation; visible in admin transaction detail', priority: 'P2', type: 'Functional' },
      { id: 'PY001', feature: 'Multi-currency enable and display order', verify: 'Drag order persists; checkout currency dropdown reflects saved order', priority: 'P0', type: 'Functional' },
      { id: 'PY002', feature: 'Currency lock after completed donations', verify: 'Default currency field disabled on Donation Forms / Campaigns that have completed donations', priority: 'P0', type: 'Data Integrity' },
      { id: 'PY003', feature: 'Payment gateway credentials save Stripe, PayPal)', verify: 'Credentials encrypt in DB; live transactions processed; test/sandbox mode works', priority: 'P0', type: 'Integration' },
      { id: 'PY004', feature: 'Currency geolocation rules apply on public pages', verify: 'Visitor from configured country/region sees correct currency pre-selected', priority: 'P1', type: 'Integration' },
      { id: 'PY005', feature: 'Receipt threshold: auto-generate above minimum', verify: 'Donations above threshold generate receipt PDF; below do not', priority: 'P1', type: 'Functional' },
      { id: 'PY006', feature: 'DAFpay: enable/disable hides from checkout', verify: 'When module off, DAF option absent from checkout page and gateway list', priority: 'P1', type: 'Functional' },
      { id: 'PY007', feature: 'DAFpay: grant completion flow end-to-end', verify: 'POST /api/daf/complete processes correctly; order recorded with DAF metadata', priority: 'P0', type: 'E2E' },
      { id: 'PY008', feature: 'DAF merge tags in receipts render correctly', verify: 'fund_name, tracking_id, chariot_grant_id populate in receipt PDF and email', priority: 'P1', type: 'Integration' },
      { id: 'LT001', feature: 'Language toggle: English, Hebrew, French, Spanish', verify: 'Enabled languages appear in public language switcher; disabled ones do not', priority: 'P1', type: 'Functional' },
      { id: 'LT002', feature: 'Hebrew auto-triggers RTL on public and admin UI', verify: 'When Hebrew is active language, both admin portal and public pages render RTL', priority: 'P1', type: 'UI/Visual' },
      { id: 'LT003', feature: 'Timezone affects all date/time display', verify: 'Donation timestamps, event schedules, and report dates all reflect configured timezone', priority: 'P1', type: 'Functional' },
      { id: 'RG001', feature: 'Account field: required/visible/enabled toggles', verify: 'Each combination correctly shows/hides/enforces field on public registration', priority: 'P0', type: 'Functional' },
      { id: 'RG002', feature: 'Participant and team fields configurable independently', verify: 'Step 2 (team) and Step 3 (fundraiser page) field configs are independent', priority: 'P1', type: 'Functional' },
      { id: 'RG003', feature: 'Custom fields appear read-only in registration tab', verify: 'Custom field list shown; changes must be made via Custom Fields module', priority: 'P2', type: 'Functional' },
    ],
  },
  {
    code: '05',
    title: 'Media library',
    tasks: [
      { id: 'ML001', feature: 'Upload via drag-and-drop and file browser', verify: 'Files appear in grid immediately after upload; metadata (size, dimensions, MIME correct', priority: 'P1', type: 'Functional' },
      { id: 'ML002', feature: 'Cursor-based pagination for large libraries', verify: 'Large media libraries paginate without performance degradation; no missing files', priority: 'P1', type: 'Performance' },
      { id: 'ML003', feature: 'Search by filename', verify: 'Results match filename substring; no false positives', priority: 'P2', type: 'Functional' },
      { id: 'ML004', feature: 'MIME type filter', verify: 'Filtering by JPEG/PNG/WebP/SVG shows only matching files', priority: 'P2', type: 'Functional' },
      { id: 'ML005', feature: 'Alt text editing and saving', verify: 'Alt text saves correctly; renders as alt attribute on public image tags', priority: 'P1', type: 'Accessibility' },
      { id: 'ML006', feature: 'Delete confirmation and permanent removal', verify: 'Deleted file no longer accessible; references in branding/campaigns show broken state (logged)', priority: 'P1', type: 'Functional' },
      { id: 'ML007', feature: 'Media Picker selects and returns file to parent form', verify: 'Selecting image in picker closes picker; parent form shows preview of selected file', priority: 'P0', type: 'Functional' },
      { id: 'ML008', feature: 'Automatic image conversion on upload', verify: 'Optimized default conversion generated; original preserved; sizes stored correctly', priority: 'P1', type: 'Functional' },
      { id: 'ML009', feature: 'Media Library accessible from Website Builder shortcut', verify: 'Builder side panel link opens media library; builder context stays open on return', priority: 'P2', type: 'Functional' },
    ],
  },
  {
    code: '06',
    title: 'Dashboard & analytics',
    tasks: [
      { id: 'DB001', feature: 'Stat cards: Today, This Month, This Year', verify: 'Amounts correct; percentage change vs prior period accurate; sparklines show last 7 data points', priority: 'P1', type: 'Data Integrity' },
      { id: 'DB002', feature: 'Giving Trends chart: 7/30/90 day views', verify: 'Tab switching updates chart; sources Campaigns, eCards, Sponsorships, Forms) correctly segmented', priority: 'P1', type: 'Functional' },
      { id: 'DB003', feature: 'Campaign goal progress bars', verify: 'Active campaigns display with correct raised/goal ratio and visual bar', priority: 'P1', type: 'Data Integrity' },
      { id: 'DB004', feature: 'Top Forms and Top Fundraisers tables', verify: 'Rankings accurate; conversion rate calculation correct; average donation correct', priority: 'P1', type: 'Data Integrity' },
      { id: 'DB005', feature: 'Donor Health Score 0100', verify: 'Score reflects actual donor engagement data; benchmark comparison renders', priority: 'P2', type: 'Data Integrity' },
      { id: 'DB006', feature: 'AI Recommendations render', verify: 'At least one recommendation present; no broken states or empty panels', priority: 'P2', type: 'Functional' },
      { id: 'DB007', feature: 'Donor Segments: Active / At-Risk / Lapsed', verify: 'Segment counts match expected business logic; recalculate after new donations', priority: 'P1', type: 'Data Integrity' },
      { id: 'DB008', feature: 'Conversion Funnel: page views → starts → completions', verify: 'Drop-off percentages mathematically correct; abandonment rate = 100% - conversion rate', priority: 'P1', type: 'Data Integrity' },
      { id: 'DB009', feature: 'Top Regions and Device Breakdown', verify: 'Geographic and device data renders; percentages sum to 100%', priority: 'P2', type: 'Data Integrity' },
      { id: 'DB010', feature: 'Dashboard accessible to all authenticated users', verify: 'No permission gate required; all role types see dashboard on login', priority: 'P0', type: 'Security' },
    ],
  },
  {
    code: '07',
    title: 'Dynamic elements',
    tasks: [
      { id: 'SP001', feature: 'Create sponsorship with multi-currency pricing', verify: 'One price field per enabled currency; must enter at least one price to save', priority: 'P0', type: 'Functional' },
      { id: 'SP002', feature: 'Sponsorship status: Draft / Active / Inactive', verify: 'Draft hidden from public forms; Active visible; Inactive hidden without data loss', priority: 'P0', type: 'Functional' },
      { id: 'SP003', feature: 'Multi-language title/description (per language)', verify: 'Prices and images shared; title/description editable per language version', priority: 'P1', type: 'Functional' },
      { id: 'SP004', feature: 'Duplicate sponsorship', verify: 'Copy created with identical settings; duplicate is Draft by default', priority: 'P2', type: 'Functional' },
      { id: 'SP005', feature: 'Delete sponsorship confirmation', verify: 'Confirmation dialog shows name; deletion is permanent; cannot delete if in active use (warning shown)', priority: 'P1', type: 'Functional' },
      { id: 'SP006', feature: 'Language filter on listing defaults to current site language', verify: 'Filter pre-selects active site language; switching language updates list', priority: 'P2', type: 'Functional' },
      { id: 'RC001', feature: 'Create receipt template with all sections', verify: 'Header, body, signature, thank-you, tax disclaimer all save; merge tags render in preview', priority: 'P0', type: 'Functional' },
      { id: 'RC002', feature: 'Receipt template types behave correctly', verify: 'Canadian options visible only when CAD enabled; Event fields present for event type', priority: 'P1', type: 'Functional' },
      { id: 'RC003', feature: 'Merge tags in body render correctly', verify: 'Donor name, amount, date, receipt number, address all populate from order data', priority: 'P0', type: 'Functional' },
      { id: 'RC004', feature: 'Publish/unpublish from listing', verify: 'Published templates available for PDF generation; unpublished not selectable', priority: 'P1', type: 'Functional' },
      { id: 'RC005', feature: 'Regenerate PDF from transaction detail', verify: 'Selecting template and clicking Regenerate creates/updates PDF; Download link works', priority: 'P0', type: 'Functional' },
      { id: 'TC001', feature: 'Create tribute card with all styling options', verify: 'Colors (heading, text, border, background), logo, date toggle all save', priority: 'P1', type: 'Functional' },
      { id: 'TC002', feature: 'Live preview updates in real time', verify: 'Typing header/body or changing colors updates preview immediately without save', priority: 'P1', type: 'UI/Visual' },
      { id: 'TC003', feature: 'Tribute card rendered in email via merge tag', verify: '{{tribute_cards.card.{id}}} token replaced with card HTML at send time', priority: 'P0', type: 'Integration' },
      { id: 'EC001', feature: 'Create eCard with prices per currency', verify: 'At least one price required; all active currencies shown', priority: 'P0', type: 'Functional' },
      { id: 'EC002', feature: 'eCard body pre-fills from organization bio/name', verify: 'Body and signing fields auto-populate on new eCard; overridable per eCard', priority: 'P2', type: 'Functional' },
      { id: 'EC003', feature: 'Live preview updates in real time', verify: 'Heading, body, colors, images update preview without save', priority: 'P1', type: 'UI/Visual' },
      { id: 'EC004', feature: 'eCard Settings: BCC email saves and applies', verify: 'All delivery emails include configured BCC address', priority: 'P1', type: 'Functional' },
      { id: 'EC005', feature: 'eCard module toggle hides all eCard surfaces', verify: 'Disabling module removes tab, widget picker option, and public widget output', priority: 'P0', type: 'Functional' },
    ],
  },
  {
    code: '08',
    title: 'Custom fields',
    tasks: [
      { id: 'CF001', feature: 'All 8 field types create successfully', verify: 'Text, Number, Date, Dropdown, Checkbox, Multi-Select, URL, Email all save and render on forms', priority: 'P0', type: 'Functional' },
      { id: 'CF002', feature: 'Internal name: unique, lowercase, underscores only', verify: 'Invalid internal names rejected with clear error; duplicates rejected', priority: 'P1', type: 'Functional' },
      { id: 'CF003', feature: 'Dropdown and Multi-Select options management', verify: 'Add/remove options; at least one required; order displays as entered', priority: 'P1', type: 'Functional' },
      { id: 'CF004', feature: 'Validation: Required toggle enforces on forms', verify: 'Required field blocks submission when empty; error message shown', priority: 'P0', type: 'Functional' },
      { id: 'CF005', feature: 'Validation: Number min/max enforces', verify: 'Values outside range rejected at submission', priority: 'P1', type: 'Functional' },
      { id: 'CF006', feature: 'Validation: Regex pattern enforces on Text/URL/Email', verify: 'Non-matching input rejected; error shown', priority: 'P1', type: 'Functional' },
      { id: 'CF007', feature: 'Entity assignment: Contacts, Donation Forms, Campaigns', verify: 'Field appears only on assigned entity types; one field can be on multiple entities', priority: 'P0', type: 'Functional' },
      { id: 'CF008', feature: 'Active/Inactive status controls availability', verify: 'Inactive fields do not appear on forms; active fields appear', priority: 'P1', type: 'Functional' },
      { id: 'CF009', feature: 'Delete: permanent with confirmation; warns about data loss', verify: 'Confirmation dialog shown; all stored values removed; cannot undo', priority: 'P1', type: 'Functional' },
      { id: 'CF010', feature: 'Custom fields appear in email merge tag catalog', verify: 'Fields with valid slug names appear as {{custom_fields.fieldname}} in email builder', priority: 'P1', type: 'Integration' },
    ],
  },
  {
    code: '09',
    title: 'Campaigns',
    tasks: [
      { id: 'CM001', feature: 'Campaign list: search, sort, filter by language', verify: 'All columns sortable; language filter works; type icon reflects campaign type', priority: 'P1', type: 'Functional' },
      { id: 'CM002', feature: 'Duplicate campaign creates draft copy', verify: 'All settings copied; new campaign in Draft status; unique slug generated', priority: 'P1', type: 'Functional' },
      { id: 'CM003', feature: 'Delete requires no active orders', verify: 'Campaign with active orders shows error; campaign without orders deletes after confirmation', priority: 'P0', type: 'Data Integrity' },
      { id: 'CM004', feature: 'Campaign status: Draft / Active / Inactive', verify: 'Publish permission required to set Active; without it, save keeps Draft', priority: 'P0', type: 'Security' },
      { id: 'CM005', feature: 'Campaign Dashboard: Overview, Donations, Participants, Teams tabs', verify: 'All 4 tabs load correct data; search and Add Filter work on each tab', priority: 'P1', type: 'Functional' },
      { id: 'CM006', feature: 'Required fields: Title, Start Date, End Date, Goal Amount', verify: 'Save blocked without all required fields; clear validation messages shown', priority: 'P0', type: 'Functional' },
      { id: 'CM007', feature: 'No End Date checkbox hides end date field', verify: 'Campaign runs indefinitely; end date field hidden from editor and public page', priority: 'P1', type: 'Functional' },
      { id: 'CM008', feature: 'Confetti celebration on goal reached', verify: 'Confetti animation fires when campaign hits 100%; Off/on-goal/always modes work', priority: 'P2', type: 'UI/Visual' },
      { id: 'CM009', feature: 'Campaign URL unique slug, copy, QR code', verify: 'Duplicate slug rejected with error; QR code downloadable; link functional', priority: 'P0', type: 'Functional' },
      { id: 'CM010', feature: 'Default currency locked after completed donations', verify: 'Currency field disabled once campaign has at least one completed donation', priority: 'P0', type: 'Data Integrity' },
      { id: 'CM011', feature: 'Hide Currency Switcher: donation form stays in default currency', verify: 'Header display currency changes do not affect embedded donation form currency', priority: 'P1', type: 'Functional' },
      { id: 'CM012', feature: 'Form settings: one-time and monthly donation configuration', verify: 'At least one frequency must be enabled; button text customizable; monthly duration options work', priority: 'P0', type: 'Functional' },
      { id: 'CM013', feature: 'Template style: Traditional / Modern / Event', verify: 'Each layout style renders correctly on public campaign page', priority: 'P1', type: 'UI/Visual' },
      { id: 'CM014', feature: 'Font override: campaign-level fonts override org defaults', verify: 'Custom fonts apply only to this campaign; other campaigns unaffected', priority: 'P1', type: 'UI/Visual' },
      { id: 'CM015', feature: 'Color override: 7 colors customizable per campaign', verify: 'Override toggle activates color pickers; colors apply to public page', priority: 'P1', type: 'UI/Visual' },
      { id: 'CM016', feature: 'Campaign wording: participant labels and button text', verify: 'Custom labels appear on public campaign page and header builder preview', priority: 'P2', type: 'Functional' },
      { id: 'CM017', feature: 'Campaign header override works independently', verify: 'Override only affects this campaign; default header template unchanged; per-language', priority: 'P1', type: 'Functional' },
      { id: 'CM018', feature: 'Page sections: reorder, enable/disable', verify: 'Drag to reorder works; disabled sections absent from public page', priority: 'P1', type: 'Functional' },
      { id: 'CM019', feature: 'Gallery images: multiple upload and display', verify: 'Multiple images uploadable; all display on public campaign page', priority: 'P2', type: 'Functional' },
      { id: 'CM020', feature: 'Page visibility toggles (goal, amount, countdown, etc.)', verify: 'All 6 hide/show toggles work correctly on public page', priority: 'P1', type: 'Functional' },
      { id: 'P2P001', feature: 'Enable individual participants: public registration works', verify: 'Participants can register and create fundraising pages end-to-end', priority: 'P0', type: 'E2E' },
      { id: 'P2P002', feature: 'Admin approval required for participants', verify: 'New pages shown as pending; admin can approve/reject; notification sent on approval', priority: 'P0', type: 'E2E' },
      { id: 'P2P003', feature: 'Enable teams: team registration and captain assignment', verify: 'Teams can be created; captain link on team page opens captain\'s page', priority: 'P0', type: 'E2E' },
      { id: 'P2P004', feature: 'Campaign type auto-detected from settings', verify: 'Basic / P2P / Team / Event type icon reflects configured options without manual selection', priority: 'P1', type: 'Functional' },
      { id: 'P2P005', feature: 'Participant page breadcrumb: Campaign > Team > Participant', verify: 'Context never lost; each segment clickable', priority: 'P1', type: 'UI/Visual' },
      { id: 'P2P006', feature: 'Bulk approve/reject participants and teams', verify: 'Checkbox selection + bulk action applies to all selected rows', priority: 'P1', type: 'Functional' },
      { id: 'P2P007', feature: 'Move participant between teams (with/without fund transfer)', verify: 'Team assignment updates; Transfer raised funds option moves giving attribution correctly', priority: 'P0', type: 'Data Integrity' },
      { id: 'AD001', feature: 'Sponsorships addon: attach to campaign', verify: 'Active sponsorships selectable; appear in checkout flow', priority: 'P1', type: 'Integration' },
      { id: 'AD002', feature: 'Matching campaign: configure matchers', verify: 'Matcher count and details save; matching visible on public campaign', priority: 'P1', type: 'Functional' },
      { id: 'AD003', feature: 'Bonus Round: activates after main goal reached', verify: 'Bonus goal displays after campaign 100%; separate target amount works', priority: 'P1', type: 'Functional' },
      { id: 'AD004', feature: 'Goals: allow participants to choose fundraising goals', verify: 'Goal library items selectable; Hide Other removes free-form option', priority: 'P1', type: 'Functional' },
      { id: 'AD005', feature: 'Commitments: payment gateway and installments', verify: 'Commitment flow end-to-end; deadline enforces; re-commitments modal on deadline end', priority: 'P1', type: 'E2E' },
      { id: 'AD006', feature: 'Sign-up fee: charged at registration', verify: 'Fee amount deducted; label displays to participant; fee orders visible on campaign pages', priority: 'P0', type: 'E2E' },
      { id: 'AD007', feature: 'Integration fields: Salesforce, Blackbaud, Admire', verify: 'All ID fields save; integration enabled/disabled independently per campaign', priority: 'P2', type: 'Integration' },
      { id: 'AD008', feature: 'Split donations: donor splits across multiple designations', verify: 'Split UI appears at checkout; each designation recorded in order line items', priority: 'P1', type: 'Functional' },
      { id: 'AD009', feature: 'Product tags on campaigns: add, filter, export', verify: 'Tags persist; tag filter works on campaign list; exports respect filter', priority: 'P1', type: 'Functional' },
      { id: 'ML010', feature: 'Add language version: copies settings, unique slug', verify: 'New locale has own slug; fundraising data shared with primary record', priority: 'P0', type: 'Functional' },
      { id: 'ML011', feature: 'Donations on any locale URL record to primary record', verify: 'Stats and totals update identically across all language URLs', priority: 'P0', type: 'Data Integrity' },
      { id: 'ML012', feature: 'Language switcher on public campaign page redirects correctly', verify: 'Switching language sends visitor to correct localized URL for that campaign', priority: 'P1', type: 'Functional' },
      { id: 'ML013', feature: 'RTL layout on Hebrew campaign page', verify: 'Hebrew campaign page renders RTL without layout breaks', priority: 'P1', type: 'UI/Visual' },
      { id: 'SEO001', feature: 'SEO fields: title, description, image, alt', verify: 'Meta tags render correctly in HTML head; social share image loads', priority: 'P1', type: 'Functional' },
      { id: 'URL001', feature: 'URL rename creates 301 redirect from old slug', verify: 'Old URL redirects to new URL; redirect chain maintained across multiple renames', priority: 'P0', type: 'Functional' },
      { id: 'URL002', feature: 'Draft/Inactive campaigns return 404 for old slugs', verify: 'Redirects do not fire for non-active campaigns', priority: 'P1', type: 'Functional' },
      { id: 'URL003', feature: 'Renaming back to previous slug removes redirect loop', verify: 'Re-using old slug removes it from redirect history; no infinite redirect', priority: 'P0', type: 'Functional' },
      { id: 'URL004', feature: 'Team URL rename: only last segment editable', verify: 'Campaign prefix fixed; team slug editable; old URL redirects', priority: 'P1', type: 'Functional' },
      { id: 'URL005', feature: 'Participant URL auto-updates when team changes', verify: 'Participant slug gains/loses team segment after team reassignment; old URL still redirects', priority: 'P1', type: 'Functional' },
    ],
  },
  {
    code: '10',
    title: 'Emails & transactional messages',
    tasks: [
      { id: 'EM001', feature: 'Email manager: trigger, scheduled, abandon, settings tabs', verify: 'All 4 tabs accessible; URLs update per tab; bookmarks stable', priority: 'P1', type: 'Functional' },
      { id: 'EM002', feature: 'Create template: 5-step wizard completes without error', verify: 'Module → Recipient → Trigger → Configuration → Content; all steps navigable; Cancel returns without saving', priority: 'P1', type: 'Functional' },
      { id: 'EM003', feature: 'Merge tags: catalog loads correct tags per module', verify: 'Tags change when module changes; only valid tags appear in picker for selected trigger', priority: 'P0', type: 'Functional' },
      { id: 'EM004', feature: 'Invalid merge tokens block save', verify: 'Unknown tokens in subject/body rejected on save with clear error', priority: 'P0', type: 'Functional' },
      { id: 'EM005', feature: 'Preview: merge tags replaced with sample data', verify: 'Preview shows merged HTML; unknown tokens optionally visible in draft mode', priority: 'P1', type: 'Functional' },
      { id: 'EM006', feature: 'Test send: delivered to specified recipient', verify: 'Test email arrives; From/From name resolved in priority order; Reply-To applied', priority: 'P1', type: 'E2E' },
      { id: 'EM007', feature: 'Development mode: logs only, no real delivery', verify: 'When on, no emails delivered; log shows "Dev mode (not sent)"; resend also suppressed', priority: 'P0', type: 'Functional' },
      { id: 'EM008', feature: 'Enable/disable toggle: disabled templates do not send', verify: 'Disabled template is not triggered when its event fires', priority: 'P0', type: 'Functional' },
      { id: 'EM009', feature: 'Send delay applies correctly', verify: 'Emails queue for configured delay; payment-failed email not sent if donor completes payment before delay', priority: 'P1', type: 'Functional' },
      { id: 'EM010', feature: 'Country/currency targeting filters messages', verify: 'Templates scoped to specific country/currency only fire for matching orders', priority: 'P1', type: 'Functional' },
      { id: 'EM011', feature: 'Product-level email override: use global / override / do not send', verify: 'Each mode behaves as documented; product-only emails not visible in Email Manager hub', priority: 'P1', type: 'Functional' },
      { id: 'EM012', feature: 'Product-level Add Email creates campaign/form-only template', verify: 'Extra email sends only for that product; does not affect global hub', priority: 'P1', type: 'Functional' },
      { id: 'EM013', feature: 'Order sent emails: view full message in transaction detail', verify: 'Envelope, headers, rendered HTML, attachments all visible in dialog', priority: 'P1', type: 'Functional' },
      { id: 'EM014', feature: 'Resend from order: edit body, select attachments, send', verify: 'Resend triggers new delivery; new entry logged; order sent-email list refreshes', priority: 'P1', type: 'E2E' },
      { id: 'EM015', feature: 'Crowdfunding email triggers: participant and team notifications', verify: 'Donation on participant page → participant and admin notified;', priority: 'P0', type: 'E2E' },
      { id: 'EM016', feature: 'Goal milestone emails fire at 25/50/75/100% once only', verify: 'Milestone triggers once per campaign/participant/team; not repeated on subsequent donations', priority: 'P0', type: 'E2E' },
      { id: 'EM017', feature: 'Tribute card token renders HTML card in email', verify: '{{tribute_cards.card.{id}}} replaced with correct card design at send time', priority: 'P0', type: 'Integration' },
      { id: 'EM018', feature: 'Recipient groups: named admin email lists', verify: 'Groups save in settings; templates using group recipients deliver to all group members', priority: 'P1', type: 'Functional' },
    ],
  },
  {
    code: '11',
    title: 'Control center: logs & audit',
    tasks: [
      { id: 'LOG001', feature: 'Email logs: filter by receiver, read status, date range', verify: 'Filtered results match; multiple receiver addresses via comma-separated params', priority: 'P1', type: 'Functional' },
      { id: 'LOG002', feature: 'Email log row: delivery status Sent / Dev mode / Failed)', verify: 'Each status renders correctly; read status shows — for Dev mode rows', priority: 'P1', type: 'Functional' },
      { id: 'LOG003', feature: 'Email log: View Template links to correct editor', verify: 'Global template → Email Manager; product override → product Emails tab', priority: 'P1', type: 'Functional' },
      { id: 'LOG004', feature: 'Email log: Resend from detail panel', verify: 'Resend delivers fresh copy; new log entry created; Dev mode suppresses resend', priority: 'P1', type: 'E2E' },
      { id: 'LOG005', feature: 'eCard logs: edit delivery before send', verify: 'Recipient name, email, message, schedule all editable before eCard is sent', priority: 'P1', type: 'Functional' },
      { id: 'LOG006', feature: 'eCard logs: Send Now for Pending/Scheduled rows', verify: 'Triggers immediate delivery; confirmation dialog required', priority: 'P1', type: 'Functional' },
      { id: 'LOG007', feature: 'Receipt logs: View PDF, Download, Resend', verify: 'PDF opens in new tab; download saves file; resend delivers email to donor', priority: 'P0', type: 'Functional' },
      { id: 'LOG008', feature: 'Audit logs: filter by user, event type, entity, date', verify: 'All filter combinations work; search returns accurate results', priority: 'P2', type: 'Functional' },
      { id: 'LOG009', feature: 'Export CSV/XLSX on all log types requires export permission', verify: 'Users without export permission: no button visible; API returns 403', priority: 'P0', type: 'Security' },
      { id: 'LOG010', feature: 'Legacy URLs redirect to Control Center routes', verify: '/admin/logs and /admin/logs/audit redirect correctly without 404', priority: 'P2', type: 'Functional' },
    ],
  },
  {
    code: '12',
    title: 'Contacts & CRM',
    tasks: [
      { id: 'CR001', feature: 'Advanced donor search: All / Any / None word lists', verify: 'AND, OR, NOT logic applied correctly; results match expected behavior', priority: 'P1', type: 'Functional' },
      { id: 'CR002', feature: 'Boolean-style main search: (term) AND/OR/NOT expressions', verify: 'Parentheses and keywords parsed; plain text falls back to normal search', priority: 'P1', type: 'Functional' },
      { id: 'CR003', feature: 'Search matches across all CRM fields (not just grid columns)', verify: 'Results reflect matches in notes, orders, custom fields, related data', priority: 'P1', type: 'Functional' },
      { id: 'CR004', feature: 'Clear advanced search: resets all lists and table', verify: 'Table reloads with no filters; modal state cleared', priority: 'P2', type: 'Functional' },
      { id: 'CR005', feature: 'Fundraisers list: search, filter, view workspace', verify: 'Name/email search works; clicking row opens participant workspace', priority: 'P1', type: 'Functional' },
      { id: 'CR006', feature: 'Participant workspace: Campaigns & Teams tab data correct', verify: 'Raised total, donor count, team name, and campaign all accurate', priority: 'P1', type: 'Data Integrity' },
      { id: 'CR007', feature: 'Change team assignment with/without fund transfer', verify: 'Team updates correctly; with transfer, raised amount migrates; without, old attribution stays', priority: 'P0', type: 'Data Integrity' },
      { id: 'CR008', feature: 'Edit Profile: update name, email, phone on participant', verify: 'Changes persist; fundraising identity updated across platform', priority: 'P1', type: 'Functional' },
    ],
  },
  {
    code: '13',
    title: 'Payment links',
    tasks: [
      { id: 'PL001', feature: 'Create payment link with title, price, currency', verify: 'Link saves; public URL accessible after publish; correct price displayed', priority: 'P0', type: 'Functional' },
      { id: 'PL002', feature: 'Allow custom price entry on checkout', verify: 'When enabled, donor can change amount; when disabled, amount is fixed', priority: 'P1', type: 'Functional' },
      { id: 'PL003', feature: 'Currency switcher toggle shows/hides on checkout', verify: 'Enabled shows dropdown; disabled shows only default currency', priority: 'P1', type: 'Functional' },
      { id: 'PL004', feature: 'Additional fees: label, items, selected by default', verify: 'Fee items render at checkout; pre-selected fees included by default; donor can deselect', priority: 'P1', type: 'Functional' },
      { id: 'PL005', feature: 'Only published links accessible at public URL', verify: 'Draft link returns 404 or redirect; published link renders checkout', priority: 'P0', type: 'Functional' },
      { id: 'PL006', feature: 'Checkout link copy button copies correct URL', verify: 'Copied URL matches /pay/{slug}; opens functional checkout in new tab', priority: 'P1', type: 'Functional' },
      { id: 'PL007', feature: 'Duplicate creates new draft with same settings', verify: 'Copy has unique slug; original unchanged; duplicate in Draft state', priority: 'P2', type: 'Functional' },
    ],
  },
  {
    code: '14',
    title: 'Website builder, pages, posts & widgets',
    tasks: [
      { id: 'WB001', feature: 'Website Builder opens as extra sidebar column', verify: 'Builder column appears beside sidebar; does not replace it; closes cleanly', priority: 'P1', type: 'UI/Visual' },
      { id: 'WB002', feature: 'Builder stays open while navigating Pages, Posts, Media', verify: 'Column persists across all builder sub-sections; closes only when navigating away', priority: 'P1', type: 'Functional' },
      { id: 'WB003', feature: 'Templates: Header tab shows main and default campaign headers', verify: 'Two builders stacked; language picker changes which template is edited', priority: 'P1', type: 'Functional' },
      { id: 'WB004', feature: 'Header: background and link colors, items, mobile settings', verify: 'All 3 setting areas save; live preview updates; mobile menu modes both work', priority: 'P1', type: 'Functional' },
      { id: 'WB005', feature: 'Header: item visibility toggle and reorder', verify: 'Eye icon hides item; drag handle reorders; Space item pushes content right', priority: 'P1', type: 'Functional' },
      { id: 'WB006', feature: 'Page Includes: Landing / Header / Footer / Header & Footer', verify: 'Each option renders correct chrome on public page; Landing hides both', priority: 'P1', type: 'Functional' },
      { id: 'WB007', feature: 'Tags: create, edit, delete tags with color', verify: 'Tags saved with name, slug, color; slug auto-generated; edit/delete confirm dialog', priority: 'P1', type: 'Functional' },
      { id: 'WB008', feature: 'Categories: hierarchy, parent assignment, unique slugs', verify: 'Subcategories render under parent; cannot set own parent to descendant (loop prevented)', priority: 'P1', type: 'Functional' },
      { id: 'WB009', feature: 'Posts: create with category (required), tags, SEO', verify: 'Save blocked without category; URL prefix reflects category path', priority: 'P0', type: 'Functional' },
      { id: 'WB010', feature: 'Posts: publish, duplicate, delete with confirmation', verify: 'Status changes work; duplicate creates draft copy; delete requires confirmation', priority: 'P1', type: 'Functional' },
      { id: 'WB011', feature: 'Widgets: 7 templates create with correct options', verify: 'Donor list, Amount raised, Leaderboard, Goal bar, Team list, Participant list, Campaign list all create', priority: 'P1', type: 'Functional' },
      { id: 'WB012', feature: 'Widget live preview updates with settings changes', verify: 'Preview card reflects source, template, and customization changes in real time', priority: 'P1', type: 'UI/Visual' },
      { id: 'WB013', feature: 'Widget embed: script tag and page builder reference', verify: 'Script embed renders widget on external site; page builder shortcode renders in CMS page', priority: 'P0', type: 'Integration' },
      { id: 'WB014', feature: 'Widget delete warns about broken embeds', verify: 'Confirmation dialog warns; after delete, widget no longer renders in embeds', priority: 'P1', type: 'Functional' },
    ],
  },
  {
    code: '15',
    title: 'Reports & report builder',
    tasks: [
      { id: 'RP001', feature: 'Report Builder: filter chips Status, Currency, Method, Frequency, Tags)', verify: 'Each filter narrows results correctly; Tags chip only appears when tags exist', priority: 'P0', type: 'Functional' },
      { id: 'RP002', feature: 'Field selection: group checkbox, individual checkboxes, rename', verify: 'Group toggle selects/deselects all; rename changes only export column header', priority: 'P1', type: 'Functional' },
      { id: 'RP003', feature: '80-field column limit enforced', verify: 'Selecting 80 fields disables Preview and Export with clear message; back to 80 re-enables', priority: 'P1', type: 'Functional' },
      { id: 'RP004', feature: 'Preview shows correct row count and sample data', verify: 'Row count accurate; "nothing matches" state shows when 0 results', priority: 'P1', type: 'Data Integrity' },
      { id: 'RP005', feature: 'Export: CSV, XLSX, PDF — small direct download', verify: 'File downloads immediately; format matches selection; data matches preview', priority: 'P0', type: 'Functional' },
      { id: 'RP006', feature: 'Large export: scheduled job + email with download link', verify: 'Background job queued; email arrives with working signed URL', priority: 'P1', type: 'E2E' },
      { id: 'RP007', feature: 'Receipt PDF URL column in export', verify: 'Rows with PDF show correct URL; rows without PDF show — placeholder', priority: 'P1', type: 'Functional' },
      { id: 'RP008', feature: 'Save template: restores filters and fields', verify: 'Saved template reloads exact configuration; loading replaces current setup', priority: 'P1', type: 'Functional' },
      { id: 'RP009', feature: 'History & Scheduled: pause/resume/delete schedules', verify: 'Paused schedules do not run; resumed schedules execute on next cycle; delete confirmed', priority: 'P1', type: 'Functional' },
      { id: 'RP010', feature: 'Tags filter: multi-select shows tag names and product counts', verify: 'Count reflects number of products using that tag; filter returns matching transactions', priority: 'P1', type: 'Functional' },
      { id: 'RP011', feature: 'Report permissions: only users with correct report.X permission can access', verify: 'Users without report permission cannot view Reports in sidebar or access URL directly', priority: 'P0', type: 'Security' },
    ],
  },
  {
    code: '16',
    title: 'Accounts & connections / security',
    tasks: [
      { id: 'SEC001', feature: 'Cloudflare Turnstile: configure and enable', verify: 'Site key and masked secret key save; Turnstile runs invisibly on donation forms', priority: 'P0', type: 'Security' },
      { id: 'SEC002', feature: 'Turnstile middleware rejects invalid/missing token', verify: 'POST to /api/pay without valid token returns 422; legitimate donors not blocked', priority: 'P0', type: 'Security' },
      { id: 'SEC003', feature: 'Turnstile secret stored encrypted; masked in UI', verify: 'DB column encrypted; UI only shows masked last-4; Inertia payloads never expose plaintext', priority: 'P0', type: 'Security' },
      { id: 'SEC004', feature: 'Updating site key without re-entering secret preserves secret', verify: 'Empty secret field on save does not wipe stored secret', priority: 'P1', type: 'Functional' },
      { id: 'SEC005', feature: 'When Turnstile disabled: endpoints behave as normal', verify: 'No-op middleware; donation flow works without Turnstile token', priority: 'P1', type: 'Functional' },
      { id: 'SEC006', feature: 'Profile: name, email, avatar update', verify: 'All fields persist; avatar displays in sidebar immediately', priority: 'P1', type: 'Functional' },
      { id: 'SEC007', feature: 'Password change: requires current password', verify: 'Wrong current password rejected; new password saves and enforces on next login', priority: 'P0', type: 'Security' },
      { id: 'SEC008', feature: 'Strong password policy enforces when enabled', verify: 'Complexity rules (length, character mix) block weak passwords at save', priority: 'P1', type: 'Security' },
      { id: 'SEC009', feature: '2FA enable with QR code, verify, disable', verify: 'QR code scannable; verification code works; 2FA required on next login; disable flow works', priority: 'P0', type: 'Security' },
      { id: 'SEC010', feature: '2FA must be enabled at org level before individual users can enable it', verify: 'Individual toggle absent until org setting enabled', priority: 'P1', type: 'Functional' },
    ],
  },
  {
    code: '17',
    title: 'Public My Account (donors & fundraisers)',
    tasks: [
      { id: 'MA001', feature: 'My Account opens from header when enabled', verify: 'Link present in header for logged-in donors/fundraisers; absent for guests', priority: 'P0', type: 'Functional' },
      { id: 'MA002', feature: 'Campaigns: list, edit page, view public page', verify: 'Fundraiser can edit title, story, images, goal; changes reflect on public page', priority: 'P0', type: 'E2E' },
      { id: 'MA003', feature: 'Donors: filter by campaign, sort, send thank-you BCC email', verify: 'Thank-you email goes to selected donors; BCC protects donor privacy', priority: 'P1', type: 'E2E' },
      { id: 'MA004', feature: 'Donations & receipts: history with download link', verify: 'Gift history accurate; receipt PDF download only shown when PDF generated', priority: 'P0', type: 'Functional' },
      { id: 'MA005', feature: 'Monthly giving: pause, resume, edit, cancel', verify: 'Toggle/buttons update subscription state; failed payment card disables resume', priority: 'P0', type: 'E2E' },
      { id: 'MA006', feature: 'Account details: profile, personal info, notifications, security, fundraiser prefs, privacy', verify: 'All 6 section types save correctly; section URL parameter bookmarkable', priority: 'P1', type: 'Functional' },
      { id: 'MA007', feature: 'Privacy: data export JSON download', verify: 'Export contains profile, donation history, fundraisers, preference snapshots', priority: 'P1', type: 'Functional' },
      { id: 'MA008', feature: 'Privacy: account deletion — permanent, signs out', verify: 'Confirmation required; account gone after deletion; user signed out', priority: 'P0', type: 'Functional' },
      { id: 'MA009', feature: 'Data scoped to logged-in user only', verify: 'Cannot view another user\'s account data via URL manipulation', priority: 'P0', type: 'Security' },
      { id: 'MA010', feature: 'Fundraiser prefs: universal settings apply across campaigns', verify: 'T-shirt size, shipping address, emergency contact save; apply to all campaigns joined', priority: 'P1', type: 'Functional' },
    ],
  },
  {
    code: '18',
    title: 'eCard end-to-end flow',
    tasks: [
      { id: 'ECED001', feature: 'eCard purchase flow end-to-end', verify: 'Donor selects eCard, fills recipient details, pays; eCard delivery record created', priority: 'P0', type: 'E2E' },
      { id: 'ECED002', feature: 'eCard delivery email sent on scheduled date', verify: 'Email arrives to recipient on/after send date; merge tags correctly resolved', priority: 'P0', type: 'E2E' },
      { id: 'ECED003', feature: 'eCard merge tags: body editor vs email template scoped correctly', verify: 'Body editor shows body-only tags; email template shows full eCard-related tags', priority: 'P1', type: 'Functional' },
      { id: 'ECED004', feature: 'Admin can edit delivery details before send', verify: 'Name, email, message, schedule all editable and saved without re-sending', priority: 'P1', type: 'Functional' },
      { id: 'ECED005', feature: 'Send Now delivers immediately for Pending/Scheduled rows', verify: 'Confirmation dialog; eCard sent immediately; log records correct timestamp', priority: 'P1', type: 'Functional' },
      { id: 'ECED006', feature: 'Resend for Sent rows re-delivers without creating duplicate delivery', verify: 'Resend is a re-delivery, not a new purchase; log entry added', priority: 'P1', type: 'Functional' },
      { id: 'ECED007', feature: 'eCard widget on public page hides when module disabled', verify: 'Existing page widget disappears; re-enabling shows it again', priority: 'P0', type: 'Functional' },
    ],
  },
  {
    code: '19',
    title: 'Product tags: donation forms & campaigns',
    tasks: [
      { id: 'PT001', feature: 'Add tag on donation form via Additional > Tags sub-tab', verify: 'Type + Enter or pick suggestion; tag chip appears; removes with ×; saves', priority: 'P1', type: 'Functional' },
      { id: 'PT002', feature: 'Tags shared organization-wide: existing tags appear as suggestions', verify: 'Same tag used on two products points to one shared record; no duplicates created', priority: 'P1', type: 'Data Integrity' },
      { id: 'PT003', feature: 'Tag filter on list pages: multi-select filters correctly', verify: 'Filtered list shows only products with any of selected tags; export respects filter', priority: 'P1', type: 'Functional' },
      { id: 'PT004', feature: 'Report Builder Tags chip filters transactions correctly', verify: 'Transactions from tagged products appear; other filters still apply on top', priority: 'P0', type: 'Functional' },
      { id: 'PT005', feature: 'Tags chip absent from Report Builder when no tags exist', verify: 'Create a tag → chip appears; remove all tags → chip disappears', priority: 'P2', type: 'Functional' },
    ],
  },
  {
    code: '20',
    title: 'Cross-cutting: accessibility, performance & regression',
    tasks: [
      { id: 'A11Y001', feature: 'Keyboard-only navigation through checkout flow', verify: 'Entire donation checkout completable without mouse; tab order logical', priority: 'P0', type: 'Accessibility' },
      { id: 'A11Y002', feature: 'Phone country dial prefix keyboard accessible Enter/Arrow/Escape)', verify: 'All interactions completable without mouse per documented behavior', priority: 'P1', type: 'Accessibility' },
      { id: 'A11Y003', feature: 'All form inputs have visible labels', verify: 'No inputs with placeholder-only labeling; screen reader announces correctly', priority: 'P1', type: 'Accessibility' },
      { id: 'A11Y004', feature: 'Color contrast: primary blue on white meets AA 4.51', verify: 'LevCharity blue (#0091E9 on white checked with contrast tool', priority: 'P1', type: 'Accessibility' },
      { id: 'A11Y005', feature: 'RTL layout: all interactive elements reachable', verify: 'Hebrew/Arabic RTL layout does not create inaccessible controls', priority: 'P1', type: 'Accessibility' },
      { id: 'PERF001', feature: 'Donation checkout page load < 2s LCP', verify: 'Lighthouse LCP under 2 seconds on standard 4G connection', priority: 'P1', type: 'Performance' },
      { id: 'PERF002', feature: 'Campaign public page with P2P leaderboard < 3s', verify: 'Page with full leaderboard, donor list, and progress bar loads under 3s', priority: 'P1', type: 'Performance' },
      { id: 'PERF003', feature: 'Admin data tables: 1000 rows render without freeze', verify: 'Pagination handles large datasets; no browser freeze on load', priority: 'P1', type: 'Performance' },
      { id: 'PERF004', feature: 'Media library: 500 images browse without degradation', verify: 'Cursor-based pagination loads next page in < 1s', priority: 'P1', type: 'Performance' },
      { id: 'PERF005', feature: 'Concurrent checkout: 50 simultaneous transactions complete correctly', verify: 'No duplicate orders; all transactions recorded; no race conditions', priority: 'P0', type: 'Performance' },
      { id: 'REG001', feature: 'Complete donation: one-time, on a campaign', verify: 'End-to-end donation flow from public page to transaction in admin', priority: 'P0', type: 'Smoke/ E2E' },
      { id: 'REG002', feature: 'Complete monthly donation: subscription created', verify: 'Subscription visible in admin; next payment date correct', priority: 'P0', type: 'Smoke/ E2E' },
      { id: 'REG003', feature: 'P2P fundraiser registers and receives a donation', verify: 'Full registration → page live → donation credited to participant', priority: 'P0', type: 'Smoke/ E2E' },
      { id: 'REG004', feature: 'Receipt PDF generates and downloads', verify: 'Generated PDF opens; merge tags populated; no rendering errors', priority: 'P0', type: 'Smoke' },
      { id: 'REG005', feature: 'Admin user with limited role cannot access restricted areas', verify: 'Sidebar items absent; direct URL access returns 403', priority: 'P0', type: 'Security' },
      { id: 'REG006', feature: 'Email trigger fires after donation: receipt delivered', verify: 'Donor receives email within send delay; content correct', priority: 'P0', type: 'Smoke/ E2E' },
      { id: 'REG007', feature: 'Campaign URL rename: old URL redirects to new', verify: '301 redirect works; QR code still functional', priority: 'P0', type: 'Smoke' },
      { id: 'REG008', feature: 'eCard purchase and scheduled delivery', verify: 'eCard purchased; delivery email arrives on schedule', priority: 'P0', type: 'Smoke/ E2E' },
      { id: 'REG009', feature: 'Report export downloads correctly CSV', verify: 'Filters applied; file downloads; data matches preview', priority: 'P0', type: 'Smoke' },
      { id: 'REG010', feature: 'Custom field appears on donation form and captures data', verify: 'Custom field renders on form; submitted value saved to order', priority: 'P0', type: 'Smoke' },
    ],
  },
];
